### ISSUE TITLE
Making Sound Effects Play

### ISSUE THREAD

**Issue by Persomatey** [CanyonsCSClub/Fall2017#24]

**Comment by RoryGlenn** [comment]
/* This is not the final code but a very simple sample of what I am working on */

using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class SFX : MonoBehaviour {


	public GameObject shoot; //attach script to the shooting GameObject in unity
	public AudioClip laserGunFireLoop;

	private AudioSource source;

	void Awake () {
		
		source = GetComponent<AudioSource>();
	}
	
	void Update () {
		if (Input.GetButtonDown("Fire1")) {
			source.PlayOneShot (laserGunFireLoop, 1.0f);
		}
		
	}
}
